{{- if .Values.users }}
{{- $imagetag := printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) }}
{{- $pgenv := include "betydb.postgresqlEnv" . }}
{{- $betyenv := include "betydb.betydbEnv" . }}
{{- $pullPolicy := .Values.image.pullPolicy }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "betydb.fullname" . }}-add-user
  labels:
    {{- include "betydb.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # TODO once we have RBAC we can use initContainers to wait for a job
    #"helm.sh/hook": "post-install"
    #"helm.sh/hook-delete-policy": "pre-delete"
    #"helm.sh/hook-weight": "10"
spec:
  template:
    metadata:
      name: {{ include "betydb.name" . }}-add-user
      labels:
        {{- include "betydb.labels" . | nindent 8 }}
    spec:
      {{- with .Values.hooks.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      #{{- if or .Values.dburl .Values.dbtag }}
      #   - name: check-job
      #     image: ghcr.io/groundnuty/k8s-wait-for:v1.6
      #     imagePullPolicy: {{ .Values.image.pullPolicy }}
      #     args:
      #       - "job"
      #       - "{{ include "betydb.fullname" . }}-load-db"
      #{{- end }}
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "betydb.postgresqlEnv" . | nindent 12 }}
            - name: PGDATABASE
              value: {{ .Values.betyDatabase | quote }}
            - name: PG_TABLE
              value: "yields"
      containers:
        {{- range $index, $element := .Values.users }}
        - name: bety-add-user-{{ $index }}
          image: {{ $imagetag | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          args:
            - user
            - {{ .username | quote }}
            - {{ .password | quote }}
            - {{ .fullname | quote }}
            - {{ .email | quote }}
            - {{ .data | quote }}
            - {{ .page | quote }}
          env:
            {{- $pgenv | nindent 12 }}
            {{- $betyenv | nindent 12 }}
        {{- end }}
{{- end }}
