apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "betydb.fullname" . }}-hooks
  labels:
    {{- include "betydb.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - list
  - watch
  - get
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]