apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "betydb.fullname" . }}
  labels:
    {{- include "betydb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "betydb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "betydb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.customization }}
      volumes:
      {{- if .Values.customization.application }}
        - name: application-config
          configMap:
            name: {{ include "betydb.fullname" . }}-application
            items:
              - key: application.yml
                path: application.yml
      {{- end }}
      {{- if .Values.customization.logos }}
        - name: logos-volume
          configMap:
            name: {{ include "betydb.fullname" . }}-logos
      {{- end }}
      {{- end }}
      initContainers:
        - name: check-postgresql
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "betydb.postgresqlEnv" . | nindent 12 }}
            - name: PGDATABASE
              value: {{ .Values.betyDatabase | quote }}
            - name: PG_TABLE
              value: "sessions"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bety
              containerPort: 8000
              protocol: TCP
          env:
            - name: UNICORN_WORKER_PROCESSES
              value: {{ .Values.workers | quote }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "betydb.fullname" . }}
                  key: secretKey
            - name: RAILS_RELATIVE_URL_ROOT
              value: {{ .Values.ingress.path | default "" | trimSuffix "/" | quote }}
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            {{- include "betydb.postgresqlEnv" . | nindent 12 }}
            {{- include "betydb.betydbEnv" . | nindent 12 }}
          {{- if .Values.customization }}
          volumeMounts:
          {{- if .Values.customization.application }}
            - name: application-config
              mountPath: /home/bety/config/application.yml
              subPath: application.yml
          {{- end }}
          {{- if .Values.customization.logos }}
            - name: logos-volume
              mountPath: /home/bety/app/assets/images/custom
          {{- end }}
          {{- end }}
          # startupProbe:
          #   httpGet:
          #     path: {{ .Values.ingress.path }}
          #     port: bety
          #   failureThreshold: 30
          #   periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: bety
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: bety
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
