apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "betydb.fullname" . }}
  labels:
    {{- include "betydb.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "Services", "configmaps"]
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get