apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betydb.fullname" . }}
  labels:
{{ include "betydb.labels" . | indent 4 }}
type: Opaque
data:
{{- if and (not .Values.postgresql.enabled) .Values.postgresql.postgresqlPassword }}
  postgresqlPassword: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
  betyPassword:  {{ .Values.betyPassword | b64enc | quote }}
  secretKey:  {{ .Values.secretKey | b64enc | quote }}
