apiVersion: v1
kind: Service
metadata:
  name: {{ include "betydb.fullname" . }}
  labels:
{{ include "betydb.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: bety
      port: {{ .Values.service.port }}
      targetPort: bety
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "betydb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
